name: gc_course_env
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - numpy
  - matplotlib
  - jupyterlab
  - meshplot
  - igl
  - pythreejs
  - pytest
  - pytest-html
  - pytest-timeout
